### PR TITLE
Use the ingress domain for the tls secret

### LINKED ISSUE #34: Create cert using domain instead of function name
Create cert using domain instead of function name

## Expected Behaviour

If we have three FunctionIngress entries all on the same domain but with differing paths, we should create 1 cert only.

## Current Behaviour

Three get created since the "name" is the function's name instead of the domain name.

## Possible Solution

Create cert using domain instead of function name. This will need a change in the annotation and / or secret name. 

## Steps to Reproduce (for bugs)

See this example for repro - https://docs.openfaas.com/reference/ssl/kubernetes-with-cert-manager/#30-rest-style-api-mapping-for-your-functions

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Change the name of the TLS secret to use the domain name. This allows
  multiple functions to use the same secret instead of creating multiple
  secrets. This reduces the complexity for REST style APIs that need
  multiple paths corresponding to multiple Functions and FunctionIngress
  on the same domain.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Closes #34

## How Has This Been Tested?

new unit test

Manual testing locally with 
* ingress-operator using `theaxer/ingress-operator:latest-35`
* latest nginx-ingress
* latest cert-manager

A secret with the expected name `nodeinfo-tls.myfaas.club-cert-9q9wm` is created
```sh
$ kubectl get secret -n openfaas
NAME                                  TYPE                                  DATA   AGE
basic-auth                            Opaque                                2      12m
default-token-df84n                   kubernetes.io/service-account-token   3      19m
ingress-operator-token-m87z4          kubernetes.io/service-account-token   3      12m
nodeinfo-tls.myfaas.club-cert-9q9wm   Opaque                                1      60s
openfaas-controller-token-fhcsv       kubernetes.io/service-account-token   3      12m
openfaas-prometheus-token-7gd24       kubernetes.io/service-account-token   3      12m
sh.helm.release.v1.openfaas.v1        helm.sh/release.v1                    1      12m

$ kubectl get ing nodeinfo-tls -oyaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
    com.openfaas.spec: '{"metadata":{"name":"nodeinfo-tls","namespace":"openfaas","selfLink":"/apis/openfaas.com/v1alpha2/namespaces/openfaas/functioningresses/nodeinfo-tls","uid":"0e8c9e99-69b9-4ef5-bf8f-b0d421be2104","resourceVersion":"5069","generation":1,"creationTimestamp":"2020-10-31T16:56:16Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"openfaas.com/v1alpha2\",\"kind\":\"FunctionIngress\",\"metadata\":{\"annotations\":{},\"name\":\"nodeinfo-tls\",\"namespace\":\"openfaas\"},\"spec\":{\"domain\":\"nodeinfo-tls.myfaas.club\",\"function\":\"nodeinfo\",\"ingressType\":\"nginx\",\"path\":\"/\",\"tls\":{\"enabled\":true,\"issuerRef\":{\"kind\":\"Issuer\",\"name\":\"letsencrypt-staging\"}}}}\n"},"managedFields":[{"manager":"kubectl","operation":"Update","apiVersion":"openfaas.com/v1alpha2","time":"2020-10-31T16:56:16Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:domain":{},"f:function":{},"f:ingressType":{},"f:path":{},"f:tls":{".":{},"f:enabled":{},"f:issuerRef":{".":{},"f:kind":{},"f:name":{}}}}}}]},"spec":{"domain":"nodeinfo-tls.myfaas.club","function":"nodeinfo","path":"/","ingressType":"nginx","tls":{"enabled":true,"issuerRef":{"name":"letsencrypt-staging","kind":"Issuer"}}}}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openfaas.com/v1alpha2","kind":"FunctionIngress","metadata":{"annotations":{},"name":"nodeinfo-tls","namespace":"openfaas"},"spec":{"domain":"nodeinfo-tls.myfaas.club","function":"nodeinfo","ingressType":"nginx","path":"/","tls":{"enabled":true,"issuerRef":{"kind":"Issuer","name":"letsencrypt-staging"}}}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /function/nodeinfo/$1
  creationTimestamp: "2020-10-31T16:56:16Z"
  generation: 1
    manager: ingress-operator
    operation: Update
    time: "2020-10-31T16:56:16Z"
    manager: nginx-ingress-controller
    operation: Update
    time: "2020-10-31T16:56:55Z"
  name: nodeinfo-tls
  namespace: openfaas
  ownerReferences:
  - apiVersion: openfaas.com/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: FunctionIngress
    name: nodeinfo-tls
    uid: 0e8c9e99-69b9-4ef5-bf8f-b0d421be2104
  resourceVersion: "5184"
  selfLink: /apis/extensions/v1beta1/namespaces/openfaas/ingresses/nodeinfo-tls
  uid: ebaa395f-6047-4cac-83a7-2f1a09b54d34
spec:
  rules:
  - host: nodeinfo-tls.myfaas.club
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - nodeinfo-tls.myfaas.club
    secretName: nodeinfo-tls.myfaas.club-cert
status:
  loadBalancer:
    ingress:
    - ip: 172.20.0.2

kubectl get functioningress nodeinfo-tls  -oyaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openfaas.com/v1alpha2","kind":"FunctionIngress","metadata":{"annotations":{},"name":"nodeinfo-tls","namespace":"openfaas"},"spec":{"domain":"nodeinfo-tls.myfaas.club","function":"nodeinfo","ingressType":"nginx","path":"/","tls":{"enabled":true,"issuerRef":{"kind":"Issuer","name":"letsencrypt-staging"}}}}
  creationTimestamp: "2020-10-31T16:56:16Z"
  generation: 1
  name: nodeinfo-tls
  namespace: openfaas
  resourceVersion: "5069"
  selfLink: /apis/openfaas.com/v1alpha2/namespaces/openfaas/functioningresses/nodeinfo-tls
  uid: 0e8c9e99-69b9-4ef5-bf8f-b0d421be2104
spec:
  domain: nodeinfo-tls.myfaas.club
  function: nodeinfo
  ingressType: nginx
  path: /
  tls:
    enabled: true
    issuerRef:
      kind: Issuer
      name: letsencrypt-staging
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Impact to existing users

- Existing FunctionIngress will recreate new secrets when this update is installed. Users may want to remove the existing secrets.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Lucas, thanks for taking this up. Could you deploy a second FunctionIngress on the same domain, but using a different path and function to show that only one certificate is obtained?

**Comment by alexellis** [comment]
Do you have more than one FunctionIngress records with differing paths, but the same domain? I can just see the NodeInfo one

**Comment by LucasRoesler** [comment]
> Do you have more than one FunctionIngress records with differing paths, but the same domain? I can just see the NodeInfo one

One is `/` and the other is `/auth`,  both on the same domain

File: pkg/controller/controller_test.go [hunk 1]
```diff
@@ -277,3 +279,50 @@ func Test_makeRules_Traefik_NestedPath_TrimsRegex_And_TrailingSlash(t *testing.T
...
+		fni      *faasv1.FunctionIngress
+		expected []v1beta1.IngressTLS
+	}{
+		{
+			name:     "tls disabled results in empty tls config",
+			fni:      &faasv1.FunctionIngress{Spec: faasv1.FunctionIngressSpec{TLS: &faasv1.FunctionIngressTLS{Enabled: false}}},
+			expected: []v1beta1.IngressTLS{},
+		},
+		{
+			name: "tls enabled creates TLS object with corret host and secret with matching the host",
```
Comment (Waterdrips) [inline pkg/controller/controller_test.go:296]: `corret` --> `correct`

**Review by Waterdrips — APPROVED** [review]

File: pkg/controller/controller_test.go (hunk 1 above)
Comment (LucasRoesler) [reply pkg/controller/controller_test.go]: fixed

**Comment by alexellis** [comment]
You are right @LucasRoesler. Thanks
