### PR TITLE
Fix traefik annotations as they are not working properly

### LINKED ISSUE #30: [Bug] Traefik annotations don't work for any paths (except root for old Traefik versions)
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behaviour
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

All traffic destined to a domain correctly forwarded to a function regardless of the path requested.

## Current Behaviour
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

Depending on installed version of the Traefik, you may observe different behaviors.

If your Traefik version is **below v1.7.21**, then your function will receive incorrect (duplicated) path, e.g. `nodeinfo.example.com/version` will be forwarded to `gateway/function/nodeinfo/versionversion` and your function will get `/versionversion` as the path. All requests to root path (/) will be forwarded correctly to a function.

If you have Traefik **v.1.7.21 or above** then you'll get infinite redirect in attempt to request any path (even root)!

The behaviors are different because of [this issue](https://github.com/containous/traefik/issues/5990) that has been addressed in [release v1.7.21](https://github.com/containous/traefik/releases/tag/v1.7.21) of Traefik 

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

1. Traefik's rewrite target annotation should be changed from 
`traefik.ingress.kubernetes.io/rewrite-target: /function/FUNC_NAME/$1`
to
`traefik.ingress.kubernetes.io/rewrite-target: /function/FUNC_NAME`
where `FUNC_NAME` is the name of the function.
  I've created PR which fixes this issue.

2. (Nice to have) Document (where?) that Traefik v1.7.21 or above is required

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->

**Disclaimer**. I tested all of the following on linux, so not really sure that this would work on Mac or Windows.

1. Create k8s cluster locally
```
minikube start
```
2. Install traefik as ingress controller. For demonstration purposes, I first install **v1.7.20** 
```
helm upgrade -i traefik \
--version 1.87.1 \
--namespace kube-system \
--set imageTag=1.7.20 \
--set rbac.enabled=true \
--set dashboard.enabled=true \
--set dashboard.serviceType=NodePort \
--set dashboard.domain=traefik.local.dev \
--set dashboard.ingress.annotations."kubernetes\.io\/ingress\.class=traefik" \
--set deployment.hostPort.httpEnabled=true \
--set deployment.hostPort.dashboardEnabled=true \
--set serviceType=NodePort \
--set containerSecurityContext.capabilities.drop[0]=ALL \
--set containerSecurityContext.capabilities.add[0]=NET_BIND_SERVICE \
--set deploymentStrategy.type=Recreate \
stable/traefik
```
3. Install openfaas with ingress operator enabled
```
kubectl create ns dev-openfaas
kubectl create ns dev-openfaas-fn
helm upgrade -i openfaas \
--version 5.8.5 \
--namespace dev-openfaas \
--set functionNamespace=dev-openfaas-fn \
--set basic_auth=false \
--set generateBasicAuth=false \
--set ingressOperator.create=true \
--set ingress.enabled=true \
--set ingress.hosts[0].host=gateway.local.dev \
--set ingress.hosts[0].serviceName=gateway \
--set ingress.hosts[0].servicePort=8080 \
--set ingress.hosts[0].path=/ \
--set ingress.annotations."kubernetes\.io\/ingress\.class=traefik" \
openfaas/openfaas
```
4. (Optional) Add Traefik dashboard and OpenFaaS Gateway UI to your hosts if you want to access them via their domain names
```
echo "$(minikube ip) traefik.local.dev" | sudo tee -a /etc/hosts
echo "$(minikube ip) gateway.local.dev" | sudo tee -a /etc/hosts
```
or alternatively you can get their services urls to access their UIs
```
minikube -n kube-system service traefik-dashboard --url
minikube -n dev-openfaas service gateway-external --url
```

5. Deploy function
```
faas-cli deploy \
--image stefanprodan/podinfo:3.1.0 \
--namespace dev-openfaas-fn \
--name podinfo \
--annotation com.openfaas.health.http.initialDelay="2s" \
--annotation com.openfaas.health.http.path="/healthz" \
--env PODINFO_PORT="8080" \
--gateway $(minikube -n dev-openfaas service gateway-external --url) \
--tls-no-verify
```
6. Deploy FunctionIngress
```
cat <<EOF | kubectl apply -f -
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: podinfo
  namespace: dev-openfaas
spec:
  function: podinfo
  domain: podinfo.local.dev
  ingressType: "traefik"
  bypassGateway: false
  tls:
    enabled: false
EOF
```

**Now the interesting part begins**

7. Let's see what routing rule we have in Traefik for the ingress the operator created
```
curl -s $(minikube -n kube-system service traefik-dashboard --url)/api/providers/kubernetes/frontends | jq -r '.["podinfo.local.dev/"].routes'
```
Output:
```
{
  "/": {
    "rule": "PathPrefix:/;ReplacePathRegex: ^/(.*) /function/podinfo/$1$1"
  },
  "podinfo.local.dev": {
    "rule": "Host:podinfo.local.dev"
  }
}
```
Note the two `$1` at the end of the string with the rule. This is why our function gets duplicated path with this Traefik version.

8. Add function domain to your hosts and let's see how the routing works
```
echo "$(minikube ip) podinfo.local.dev" | sudo tee -a /etc/hosts
curl -s http://podinfo.local.dev
```
Output:
```
{
  "hostname": "podinfo-5569bb569c-9wvdw",
  "version": "3.1.0",
  "revision": "7b6f11780ab1ce8c7399da32ec6966215b8e43aa",
  "color": "cyan",
  "logo": "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif",
  "message": "greetings from podinfo v3.1.0",
  "goos": "linux",
  "goarch": "amd64",
  "runtime": "go1.13.1",
  "num_goroutine": "6",
  "num_cpu": "2"
}
```
And let's also request the other path
```
curl -s http://podinfo.local.dev/version
```
Output:
```
404 page not found
```
Function actually gets `/versionversion` as the path.
Let's also make sure that this path is handled by requesting it through gateway:
```
curl -s http://gateway.local.dev/function/podinfo/version
```
or
```
curl -s $(minikube -n dev-openfaas service gateway-external --url)/function/podinfo/version
```
Output:
```
{
  "commit": "7b6f11780ab1ce8c7399da32ec6966215b8e43aa",
  "version": "3.1.0"
}
```
9. Now let's change the annotation on the ingress to the proposed and see if it works with this version of Traefik
```
kubectl -n dev-openfaas annotate --overwrite ing podinfo 'traefik.ingress.kubernetes.io/rewrite-target=/function/podinfo'
curl -s http://podinfo.local.dev/version
``` 
Output:
```
error finding function podinfoenv.dev-openfaas-fn: server returned non-200 status code (404) for function, podinfoenv
```
10. Let's rollback changes to the ingress and upgrade traefik to v1.7.23 to see how things work with this version
```
kubectl -n dev-openfaas annotate --overwrite ing podinfo 'traefik.ingress.kubernetes.io/rewrite-target=/function/podinfo/$1'
helm upgrade traefik \
--namespace kube-system \
--reuse-values \
--set imageTag=1.7.23 \
stable/traefik
kubectl -n kube-system rollout status deploy/traefik
````
11. Let's request the same paths and see what we get (spoiler - infinite redirects). I intentionally limited redirects count to keep the output at acceptable level.
```
curl -sLv --max-redirs 1 http://podinfo.local.dev
```
Output:
```
* Rebuilt URL to: http://podinfo.local.dev/                                                                                                                                                                                                                                                                                                                          
*   Trying 192.168.39.39...                                                                                                                                                                                        
* TCP_NODELAY set                                                                                                                                                                                                  
* Connected to podinfo.local.dev (192.168.39.39) port 80 (#0)                                                                                                                                                      
> GET / HTTP/1.1                                                                                                                                                                                                   
> Host: podinfo.local.dev                                                                                                                                                                                          
> User-Agent: curl/7.58.0                                                                                                                                                                                          
> Accept: */*                                                                                                                                                                                                      
>                                                                                                                                                                                                                  
< HTTP/1.1 301 Moved Permanently                                                                                                                                                                                   
< Content-Length: 0
< Date: Thu, 18 Jun 2020 11:18:59 GMT
< Location: /function/podinfo/
< Vary: Accept-Encoding
< 
* Connection #0 to host podinfo.local.dev left intact
* Issue another request to this URL: 'http://podinfo.local.dev/function/podinfo/'
* Found bundle for host podinfo.local.dev: 0x5566c09a19d0 [can pipeline]
* Re-using existing connection! (#0) with host podinfo.local.dev
* Connected to podinfo.local.dev (192.168.39.39) port 80 (#0)
> GET /function/podinfo/ HTTP/1.1
> Host: podinfo.local.dev
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Date: Thu, 18 Jun 2020 11:18:59 GMT
< Location: /function/podinfo/function/podinfo/function/podinfo/
< Vary: Accept-Encoding
< 
* Connection #0 to host podinfo.local.dev left intact
* Maximum (1) redirects followed
```
```
curl -sLv --max-redirs 1 http://podinfo.local.dev/version
```
Output:
```                                                                                                                                                                                                                                                                                         
*   Trying 192.168.39.39...                                                                                                                                                                                        
* TCP_NODELAY set                                                                                                                                                                                                  
* Connected to podinfo.local.dev (192.168.39.39) port 80 (#0)                                                                                                                                                      
> GET /version HTTP/1.1                                                                                                                                                                                            
> Host: podinfo.local.dev                                                                                                                                                                                          
> User-Agent: curl/7.58.0                                                                                                                                                                                          
> Accept: */*                                                                                                                                                                                                      
>                                                                                                                                                                                                                  
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 18 Jun 2020 11:22:08 GMT
< Location: /function/podinfo/version/version
< Vary: Accept-Encoding
< 
* Connection #0 to host podinfo.local.dev left intact
* Issue another request to this URL: 'http://podinfo.local.dev/function/podinfo/version/version'
* Found bundle for host podinfo.local.dev: 0x5584618379d0 [can pipeline]
* Re-using existing connection! (#0) with host podinfo.local.dev
* Connected to podinfo.local.dev (192.168.39.39) port 80 (#0)
> GET /function/podinfo/version/version HTTP/1.1
> Host: podinfo.local.dev
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Date: Thu, 18 Jun 2020 11:22:08 GMT
< Location: /function/podinfo/function/podinfo/version/version/function/podinfo/version/version
< Vary: Accept-Encoding
< 
* Connection #0 to host podinfo.local.dev left intact
* Maximum (1) redirects followed
```

12. Now let's change the annotation on the ingress to the proposed and see how it works
```
kubectl -n dev-openfaas annotate --overwrite ing podinfo 'traefik.ingress.kubernetes.io/rewrite-target=/function/podinfo'
```
```
curl -s http://podinfo.local.dev
```
Output:
```
{
  "hostname": "podinfo-5569bb569c-9wvdw",
  "version": "3.1.0",
  "revision": "7b6f11780ab1ce8c7399da32ec6966215b8e43aa",
  "color": "cyan",
  "logo": "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif",
  "message": "greetings from podinfo v3.1.0",
  "goos": "linux",
  "goarch": "amd64",
  "runtime": "go1.13.1",
  "num_goroutine": "6",
  "num_cpu": "2"
}
```
```
curl -s http://podinfo.local.dev/version                                                                                                                                                                         
```
Output:
```
{                                                                                                                                                                                                                  
  "commit": "7b6f11780ab1ce8c7399da32ec6966215b8e43aa",                                                                                                                                                            
  "version": "3.1.0"                                                                                                                                                                                               
}
```

**Those who made this far**: Thanks for reading and don't forget to clean your hosts file at `/etc/hosts`

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
I'm trying to use ingress operator with traefik to forward all traffic from specific domain to function.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Docker version `docker version` (e.g. Docker 17.0.05 ):
`Docker version 19.03.11, build 42e35e61f3`

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T20:58:41Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS): 
`Ubuntu 18.04.4 LTS`

* Link to your project or a code example to reproduce issue:
`n/a`

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
`n/a`

### PR DESCRIPTION
**Pull request by aleks-fofanov**
Signed-off-by: Aleksandr Fofanov <avl.fofanov@gmail.com>

## Description

Please see the detailed description of the issue and context in #30

I've tested the changes to the annotation with the following function ingresses:
1.  Same as in the issue mentioned above
```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: podinfo
  namespace: dev-openfaas
spec:
  function: podinfo
  domain: podinfo.local.dev
  ingressType: "traefik"
  bypassGateway: false
  tls:
    enabled: false
```
Urls tested:
- http://podinfo.local.dev
- http://podinfo.local.dev/
- http://podinfo.local.dev/version
- http://podinfo.local.dev/delay/3
- http://podinfo.local.dev/swagger.json
- http://podinfo.local.dev/swagger/index.html

2. Function ingress with custom path
```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: podinfo
  namespace: dev-openfaas
spec:
  function: podinfo
  domain: podinfo.local.dev
  ingressType: "traefik"
  path: "/v1/(*.)"
  bypassGateway: false
  tls:
    enabled: false
```
Urls tested:
- http://podinfo.local.dev/v1
- http://podinfo.local.dev/v1/
- http://podinfo.local.dev/v1/version
- http://podinfo.local.dev/v1/delay/3
- http://podinfo.local.dev/v1/swagger.json
- http://podinfo.local.dev/v1/swagger/index.html

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Fixes #30

## How Has This Been Tested?

I've added the test that verifies that operator produce correct annotations for Traefik ingresses.
I also tested the changes to the annotations by following the steps described in #30

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Impact to existing users

This change shouldn't break anything in existing deployments.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aleks-fofanov** [comment]
@alexellis Please advise whether documentation should be updated and where exactly, I'm not sure about the right place. Thank you.

**Comment by alexellis** [comment]
Hi thanks for the PR and issue.

What kind of URLs have you tested for this fix? Have you tried subpaths and files? I.e. when serving a folder structure or varying HTTP paths with a suffix

File: pkg/controller/controller.go [hunk 1]
```diff
@@ -513,7 +513,7 @@ func makeAnnotations(fni *faasv1.FunctionIngress) map[string]string {
 			annotations["zalando.org/skipper-filter"] = `setPath("/function/` + fni.Spec.Function + `")`
 			break
 		case "traefik":
-			annotations["traefik.ingress.kubernetes.io/rewrite-target"] = "/function/" + fni.Spec.Function + "/$1"
```
Comment (alexellis) [inline pkg/controller/controller.go:516]: Why would you say that $1 is no longer required?

Comment (aleks-fofanov) [reply pkg/controller/controller.go:516]: Because traefik internally converts the annotations to the following routing rule: `PathPrefix:/;ReplacePathRegex: ^/(.*) /function/podinfo/$1$1`
Note the two replacements (`$1`). So all request will be forwarded to the function with incorrect path (older versions of Traefik, except for the root path) or won't be routed at all because of indefinite redirects (latest versions of Traefik).

**Comment by aleks-fofanov** [comment]
> What kind of URLs have you tested for this fix? Have you tried subpaths and files? I.e. when serving a folder structure or varying HTTP paths with a suffix
@alexellis I tested root path, subpaths and files too.

I also updated the docs.

**Comment by alexellis** [comment]
Please can you give an example of the FNI and the paths tested for it in the description of the PR?

**Comment by aleks-fofanov** [comment]
@alexellis Added.

**Comment by alexellis** [comment]
This is looking great. Almost ready to merge, I'd like to see a FunctionIngress that uses a path prefix now. See here: https://github.com/openfaas-incubator/ingress-operator/blob/master/README.md#schema

The idea is that you can say this function is mounted on the domain at /api/blog/v1

**Comment by alexellis** [comment]
Example for Nginx (I suspect you may want to remove the `(*.)` for Traefik, but you may know better than I do with regards to that one.

```yaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: webpage
  namespace: openfaas
spec:
  domain: "webpage.myfaas.club"
  function: "webpage"
  ingressType: "nginx"
  path: "/v1/web/(*.)" # Optionally set a path for the domain i.e. nodeinfo.myfaas.club/v1/profiles/
```

This FNI would mount the `webpage` function at `webpage.myfaas.club/v1/web/` so that anything sent there would appear as `/` in the webpage function.

**Comment by aleks-fofanov** [comment]
@alexellis Yes, thanks for the pointer to FNIs with path. Totally forgot about this feature. I fixed the routing expression for this case, tested the changes and updated the description.
**Related**: It looks to me that Ingress Operator CRD in faas-netes chart is not up-to-date with the actual spec? There is no `path` attribute the in the [spec](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/ingress-operator-crd.yaml#L23).

**Comment by alexellis** [comment]
The chart for the inlets-operator moved into the faas-netes repo here -> 

https://github.com/openfaas/faas-netes/tree/master/chart/openfaas/templates

We tend to install it like: `arkade install --ingress-operator` which generates a command like:

```
Command: /Users/alex/.arkade/bin/helm3/helm [upgrade --install openfaas openfaas/openfaas --namespace openfaas --values /var/folders/p7/ptxtv_pd3n12fd6mc5wjhk1h0000gn/T/charts/openfaas/values.yaml --set clusterRole=false --set openfaasImagePullPolicy=IfNotPresent --set faasnetes.imagePullPolicy=Always --set gateway.replicas=1 --set ingressOperator.create=true --set queueWorker.replicas=1 --set basic_auth=true --set gateway.directFunctions=true --set operator.create=false --set basicAuthPlugin.replicas=1 --set queueWorker.maxInflight=1 --set serviceType=NodePort]
```

Can you add `path` as a separate PR into the faas-netes repo?

I also noticed that you have some issues with the last few commits, we can't accept a merge commit in a PR, so can you do a rebase? `git rebase -i HEAD~N` where N is the amount of commits in total. 

Pick `s` for squash and then do a force push.

**Comment by alexellis** [comment]
Despite the CRD validation not specifying `path` as a field, it is accepted and used:

Expand to view the logs:

<details>

space-mini:vagrant alex$ kubectl apply -f -
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: webpage
  namespace: openfaas
spec:
  domain: "webpage.myfaas.club"
  function: "webpage"
  ingressType: "nginx"
  path: "/v1/web/(*.)" # Optionally set a path for the domain i.e. nodeinfo.myfaas.club/v1/profiles/
functioningress.openfaas.com/webpage created
space-mini:vagrant alex$ 
space-mini:vagrant alex$ kubectl get functioningress.openfaas.com/webpage -o yaml
Error from server (NotFound): functioningresses.openfaas.com "webpage" not found
space-mini:vagrant alex$ kubectl get functioningress.openfaas.com/webpage -o yaml -n openfaas
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openfaas.com/v1alpha2","kind":"FunctionIngress","metadata":{"annotations":{},"name":"webpage","namespace":"openfaas"},"spec":{"domain":"webpage.myfaas.club","function":"webpage","ingressType":"nginx","path":"/v1/web/(*.)"}}
  creationTimestamp: "2020-06-18T14:05:01Z"
  generation: 1
  managedFields:
  - apiVersion: openfaas.com/v1alpha2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:domain: {}
        f:function: {}
        f:ingressType: {}
        f:path: {}
    manager: kubectl
    operation: Update
    time: "2020-06-18T14:05:01Z"
  name: webpage
  namespace: openfaas
  resourceVersion: "90086"
  selfLink: /apis/openfaas.com/v1alpha2/namespaces/openfaas/functioningresses/webpage
  uid: 2c8020d3-e8a6-4520-90f9-c8731730750a
spec:
  domain: webpage.myfaas.club
  function: webpage
  ingressType: nginx
  path: /v1/web/(*.)
space-mini:vagrant alex$ 

</details>

**Comment by aleks-fofanov** [comment]
@alexellis Ok, squashed all commits in one.

> Can you add path as a separate PR into the faas-netes repo?

Yes, will try to add this on the next week.

**Comment by alexellis** [comment]
For the separate PR, can you just copy the code from my new PR? https://github.com/openfaas-incubator/ingress-operator/pull/33

It should be very quick to copy/paste from the new openfaas.com_functioningress.yaml file into the chart template in faas-netes.

Alex

**Comment by aleks-fofanov** [comment]
@alexellis https://github.com/openfaas/faas-netes/pull/656

**Comment by alexellis** [comment]
That's merged now. How are we looking for the path usecase when specific in the FunctionIngress?

**Comment by alexellis** [comment]
Very much a pleasure having this quality of contribution. Thank you again.

**Comment by alexellis** [comment]
Oh my goodness, I clearly didn't catch this, sorry.

Screenshot 2020-06-18 at 16 31 48

**Comment by aleks-fofanov** [comment]
Sorry @alexellis , all my fault. Will pay more attention to this in the future.
